MatchingSite/MatchingSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('QMLove.urls')),
    path('', include('django.contrib.auth.urls')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MatchingSite/QMLove/urls.py
from django.urls import path, include
from . import views

app_name = "QMLove"
urlpatterns = [
    path('', views.index, name="index"),
    path('register/', views.register, name="register"),
    path('search/', views.search, name="search"),
]

MatchingSite/QMLove/models.py
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime

class Hobby(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Profile(models.Model):
    GENDERS = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile_images')
    email = models.EmailField(max_length=254)
    gender = models.CharField(choices=GENDERS, max_length=1)
    dob = models.DateField(auto_now=False, auto_now_add=False)
    hobby = models.ManyToManyField(Hobby)

    def __str__(self):
        return self.user.username

    # return the age of the user
    @property
    def age(self):
        return int((datetime.now().date() - self.dob).days / 365.25)

MatchingSite/QMLove/forms.py
from django import forms
from QMLove.models import Profile, Hobby
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
import datetime
from datetime import date

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password', 'first_name', 'last_name')

class ProfileForm(forms.ModelForm):
    HOBBIES = [[hobby.id, hobby.name] for hobby in Hobby.objects.all()]
    dob = forms.DateField(widget = (forms.widgets.DateInput(format="%m/%d/%Y", attrs={'placeholder':'mm/dd/yyyy'})))
    
    def clean_dob(self):
        dobCheck = self.cleaned_data['dob']
        today = date.today()
        if (dobCheck.year + 18, dobCheck.month, dobCheck.day) > (today.year, today.month, today.day):
            raise forms.ValidationError('You must be at least 18 years old to register')
        return dobCheck
    
    image = forms.ImageField(required=False)
    hobby = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=HOBBIES)

    class Meta:
        model = Profile
        fields = ('image', 'email', 'gender', 'dob', 'hobby')

MatchingSite/QMLove/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Hobby, Profile
from QMLove.forms import UserForm, ProfileForm
from .filters import ProfileFilter
from collections import *

def index(request):
    # exclude the admin, which has id number 1
    # retrieve all the users and hobbies
    users = User.objects.all().exclude(username='admin')
    hobbies = Hobby.objects.all()

    # if the user making the request is an admin,
    # show all the records
    if request.user.is_staff:
        return render(request, "QMLove/index.html", {'users': users, 'hobbies': hobbies})

    # only execute the below code if the user is authenticated
    if (request.user.is_authenticated):
        # get the profile of the current user
        # the current user is the user that makes a request to the index page
        currentUser = Profile.objects.get(user=request.user)

        # get all the users that have common interests with the current logged in user
        # exclude the current user
        related_users = Profile.objects.filter(hobby__in=currentUser.hobby.all()).exclude(id=currentUser.id)

        # related_users returns [<Profile: user1>, <Profile: user1>, <Profile: user2>]
        # that means, the current loggedin user has two common hobbies with user1, and one common hobby with user2
        # in order to find the users with the most hobbies in common, a Counter is used
        # the Counter returns [(<Profile: user1>, 2), (<Profile: user2>, 1)]
        related_users_sorted = Counter(related_users).most_common(10)
        # extracts the users from the counter
        # similar_interests stores user1, user2, etc.
        similar_interests = [user for user,count in related_users_sorted]

        print(request.user.last_login, request.user.date_joined)

        return render(request, "QMLove/index.html", {'similar_interests': similar_interests, 'hobbies': hobbies})
    # if no user is authenticated, display all the users registered
    else:
        return render(request, "QMLove/index.html", {'users': users, 'hobbies': hobbies})

def register(request):
    if request.method == "POST":
        userForm = UserForm(data=request.POST)
        profileForm = ProfileForm(request.POST, request.FILES)
        if userForm.is_valid() and profileForm.is_valid():
            user = userForm.save()
            user.set_password(user.password)
            user.save()

            # don't commit the profile to the db yet
            # the profile needs to be associated with the user and then saved
            profile = profileForm.save(commit=False)

            # if an image has been uploaded,
            # attach it to the user's profile
            if 'image' in request.FILES:
                profile.image = request.FILES['image']

            # associate the profile with the user
            # and save it to the db
            profile.user = user
            profile.save()

            # retrieve the indexes of hobbies selected
            # so they can be iterated over and added each to profile
            # getlist is used to retrieve the indexes of hobbies selected
            hobbies = request.POST.getlist('hobby')

            # for each hobby index
            # retrieve the hobby from the db using the index
            # and add the hobby to the profile
            for index in hobbies:
                profile.hobby.add(Hobby.objects.get(id=index))

            # log in the user after registration
            login(request, user)

            return redirect('/')
        else:
            return render(request, 'QMLove/register.html', {'userForm': userForm, 'profileForm': profileForm})
    else:
        userForm = UserForm()
        profileForm = ProfileForm()
        return render(request, 'QMLove/register.html', {'userForm': userForm, 'profileForm': profileForm})

# handle the filtering
def search(request):
    # get all the profiles except the profile of the current user logged in
    profiles = Profile.objects.all().exclude(user_id=request.user.id)
    # pass the request to the ProfileFilter and the profiles
    user_filter = ProfileFilter(request.GET, queryset=profiles)
    return render(request, 'QMLove/search.html', {'filter': user_filter})

MatchingSite/QMLove/templates/QMLove/index.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html>
<head>
  {% block head %}
  <title> QMLove Homepage </title>
  {% endblock %}
</head>
<body>
  {% block body %}

  <!-- Page Content -->
  <div class="container">
    <!-- Jumbotron Header -->
    <header class="jumbotron my-4">
      <h1 class="display-3">QMLove Dating</h1>
      <p class="lead">Where the real love is born.</p>
      <hr class="my-4">
      <p>It takes a few seconds to register and find your soulmate. On the other hand, it takes a lifetime to get over the regret that you did not sign up!</p>
    </header>

    {% if user.is_authenticated %}

    {% if user.date_joined|date:"D d M Y H:i" == user.last_login|date:"D d M Y H:i" %}
      <div class="alert alert-success" role="alert">
        <p>
          Hello, {{ user }}! We want to say a warm welcome to our site! We try our best to match you with people with the most hobbies in common.
          We think that the more hobbies in common, the better the chances are that you will make a perfect couple or an ideal friendship.
        </p>

        <p>
          Thus, on this page, you will only see people that have as many hobbies in common with you as possible.
          If you want to search for people based on age, hobbies and gender go to the network page.
        </p>

        <p>
          P.S: Do not worry, the message will disappear soon!
        </p>

        <p>
          Happy surfing!
        </p>
      </div>
    {% endif %}

    {% if user.is_staff %}
      <div class="alert alert-warning" role="alert">
        <p>
          This page does not display anything for you because you are an admin.
          You do not have any hobbies, sadly, so we cannot match you with any user. :-(
        </p>

        <p>
          If you want to see all the users registered, go to the network page!
        </p>

        <p>
          Sorry!
        </p>
      </div>
    {% endif %}

    <!-- Page Features -->
    <div class="row text-center">
      {% for user in similar_interests %}
      <div class="col-3">
        <div class="card">
          <img class="card-img-top" src="/profile_images/{{ user.image }}" alt="User profile picture">
          <div class="card-body">
            <h4 class="card-title">{{ user }}</h4>
            <p class="card-text">
              Hello! I am {{ user.user.get_full_name }} and I am {{ user.age }} years old. I am looking to make some friends.
              If you want to find more about me, click on the button below!
            </p>
          </div>
          <div class="card-footer">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#{{ user.id }}">
              Find more about me!
            </button>

            <!-- Modal -->
            <div class="modal fade" id="{{ user.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title">{{ user }}'s corner</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <p class="card-text">If you clicked on me, you are surely interested in me. I am passionate about these things:
                      <ul class="list-group">
                        {% for hobby in user.hobby.all %}
                        <li class="list-group-item">{{ hobby }}</li>
                        {% endfor %}
                      </ul>
                    </p>
                    <p class="card-text">
                      <strong>Other details about me:</strong>
                      <ul class="list-group">
                        <li class="list-group-item">Email: {{ user.email }}</li>
                        <li class="list-group-item">Gender: {{ user.get_gender_display }}</li>
                        <li class="list-group-item">Date of birth: {{ user.dob }}</li>
                      </ul>
                    </p>
                    <p class="card-text">If you think we are a match, send me an email!</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}

      {% else %}

      <div class="row text-center">
        {% for user in users %}
        <div class="col-3">
          <div class="card">
            <img class="card-img-top" src="/profile_images/{{ user.profile.image }}" alt="User profile picture">
            <div class="card-body">
              <h4 class="card-title">{{ user }}</h4>
              <p class="card-text">
                Hello! I am {{ user.get_full_name }} and I am {{ user.profile.age }} years old. I am looking to make some friends.
                If you want to find more about me, click on the button below!
              </p>
            </div>
            <div class="card-footer">
              <!-- Button trigger modal -->
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#{{ user.id }}">
                Find more about me!
              </button>

              <!-- Modal -->
              <div class="modal fade" id="{{ user.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">{{ user }}'s hobbies</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <p class="card-text">If you clicked on me, you are surely interested in me. I am passionate about these things:
                        <ul class="list-group">
                          {% for hobby in user.profile.hobby.all %}
                          <li class="list-group-item">{{ hobby }}</li>
                          {% endfor %}
                        </ul>
                      </p>
                      <p class="card-text">
                        <strong>Other details about me:</strong>
                        <ul class="list-group">
                          <li class="list-group-item">Email: {{ user.profile.email }}</li>
                          <li class="list-group-item">Gender: {{ user.profile.get_gender_display }}</li>
                          <li class="list-group-item">Date of birth: {{ user.profile.dob }}</li>
                        </ul>
                      </p>
                      <p class="card-text">If you think we are a match, send me an email!</p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

        {% endif %}
      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; QMLove/Web Programming Module 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    {% endblock %}
  </body>

  </html>

MatchingSite/QMLove/templates/QMLove/register.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Register{% endblock %}


<head>
  {% block head %}
  <title> QMLove Register </title>
  {% endblock %}
</head>
<body>
  {% block body %}

  <div class="container paddingtop">
      <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <h3><li class="breadcrumb-item">Sign up</li></h3>
    </ol>
  </nav>

    <!--
    The form must contain the enctype.
    It is necessary for file (image) upload.
  -->
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}

      {% for field in userForm %}
        <div class="form-group">
          <strong><label for="{{ field.id_for_label }}"> {{ field.label_tag }} </label></strong>
          {{ field|add_class:'form-control' }}
          {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
      {% endfor %}

      {% for field in profileForm %}
        <div class="form-group">
          <strong><label for="{{ field.id_for_label }}"> {{ field.label_tag }} </label></strong>

          {% if field == profileForm.hobby %}
            {{ field|add_class:'form-group list-unstyled' }}
          {% endif %}

          {% if field != profileForm.hobby %}
            {{ field|add_class:'form-control' }}
          {% endif %}

          {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
          {% endfor %}
        </div>
      {% endfor %}

        <div class="form-group">
          <button type="submit" class="btn btn-success">
            Sign up
          </button>
        </div>
      <p></p>
    </form>
  </div>

<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; QMLove/Web Programming Module 2018</p>
  </div>
  <!-- /.container -->
</footer>
{% endblock %}
</body>


</html>

MatchingSite/QMLove/templates/QMLove/search.html
{% extends 'base.html' %}

{% load widget_tweaks %}

<!DOCTYPE html>
<html>
<head>
  {% block head %}
  <title> QMLove Network </title>
  {% endblock %}
</head>

<body>
  {% block body %}
  <div class="container">

    <header class="jumbotron my-4">
      <h1 class="display-3">QMLove Dating Network</h1>
      <p class="lead">Search for people</p>
      <hr class="my-4">
      <p>Perhaps you are not satisfied with the people our algorithm matched you. If you want to try your luck with a custom search, you are in the right place.</p>
    </header>

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item" aria-current="page">
          <form id="formFiltering" method="get">
            {% for field in filter.form %}
              <div class="form-inline">
                <strong><label for="{{ field.id_for_label }}"> {{ field.label_tag }} </label></strong>
                {{ field|add_class:'mx-sm-3 mb-2' }}
              </div>
            {% endfor %}
            <button type="submit" id="submitFiltering">Search</button>
          </form>
      </nav>

      {% if user.is_authenticated %}
      <div class="row text-center">
        {% for user in filter.qs %}
        <div class="col-3">
          <div class="card">
            <img class="card-img-top" src="/profile_images/{{ user.image }}" alt="User profile picture">
            <div class="card-body">
              <h4 class="card-title">{{ user }}</h4>
              <p class="card-text">
                Hello! I am {{ user.user.get_full_name }} and I am {{ user.age }} years old. I am looking to make some friends.
                If you want to find more about me, click on the button below!
              </p>
            </div>
            <div class="card-footer">
              <!-- Button trigger modal -->
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#{{ user.id }}">
                Find more about me!
              </button>

              <!-- Modal -->
              <div class="modal fade" id="{{ user.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">{{ user }}'s corner</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <p class="card-text">If you clicked on me, you are surely interested in me. I am passionate about these things:
                        <ul class="list-group">
                          {% for hobby in user.hobby.all %}
                          <li class="list-group-item">{{ hobby }}</li>
                          {% endfor %}
                        </ul>
                      </p>
                      <p class="card-text">
                        <strong>Other details about me:</strong>
                        <ul class="list-group">
                          <li class="list-group-item">Email: {{ user.email }}</li>
                          <li class="list-group-item">Gender: {{ user.get_gender_display }}</li>
                          <li class="list-group-item">Date of birth: {{ user.dob }}</li>
                        </ul>
                      </p>
                      <p class="card-text">If you think we are a match, send me an email!</p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    </div>

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; QMLove/Web Programming Module 2018</p>
      </div>
      <!-- /.container -->
    </footer>
    {% endblock %}
  </body>

</html>

MatchingSite/QMLove/templates/base.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
  <script src="{% static 'QMLove/popper.min.js' %}"></script>
  <script src="{% static 'QMLove/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'QMLove/bootstrap.min.js' %}"></script>
  <script src="{% static 'QMLove/filter.js' %}"></script>
  <link rel="stylesheet" href="{% static 'QMLove/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'QMLove/styles.css' %}">

  {% block head %}
  <title>QMLove</title>
  {% endblock %}

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand homelink" href="{% url 'QMLove:index' %}">QMLove</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active"> Hello, {{ user }} </a>
          </li>
          <li class="nav-item">
            <a class="nav-link homelink" href="{% url 'QMLove:index' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}" id="logout">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'QMLove:search' %}" id="search">Network</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}" id="login">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'QMLove:register' %}" id="register">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

</head>
<body>
  {% block body %}

  {% endblock %}
</body>
</html>